### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.linear_model.base'

### ISSUE THREAD

**Issue by SlvLdR** [Mogeng/IOHMM#31]
When using IOHMM with python 3.9.1 I get the following error:

> Traceback (most recent call last):
  File "c:\users\...\appdata\local\programs\python\python39\lib\site-packages\IOHMM\__init__.py", line 1, in <module>
    from .IOHMM import (UnSupervisedIOHMM,
  File "c:\users\...\appdata\local\programs\python\python39\lib\site-packages\IOHMM\IOHMM.py", line 39, in <module>
    from .linear_models import (GLM, OLS, DiscreteMNL, CrossEntropyMNL)
  File "c:\users\...\appdata\local\programs\python\python39\lib\site-packages\IOHMM\linear_models.py", line 56, in <module>
    from sklearn.linear_model.base import _rescale_data
ModuleNotFoundError: No module named 'sklearn.linear_model.base'

I managed to get it working by changing sklearn.linear_model.base to sklearn.linear_model._base in IOHMM\linear_models.py

**Comment by Mogeng** [comment]
Thanks for reporting this! Will address this in the next package.
